name: Check the source code
on:
  pull_request:
    branches:
      - *
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run prettier --check
      - name: Lint
        run: npm run eslint
